# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HuGeDJ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYCategories', '~> 1.0.4'
  pod 'FMDB', '~> 2.7.5'
  pod 'SDWebImage', '~> 4.4.5'
  
  # 列表
  pod 'MJRefresh', '~> 3.1.15.3'
  pod 'LYEmptyView', '~> 1.2.0'
  
  # model
  pod 'YYModel', '~> 1.0.4'
  pod 'MJExtension', '~> 3.0.15.1'
  
  # toast
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'Toast', '~> 4.0.0'
  
  # 键盘
  pod 'IQKeyboardManager', '~> 6.1.0'
  pod 'TPKeyboardAvoiding', '~> 1.3.2'
  
  # Router
  pod 'MGJRouterKit', '~> 0.1.2'
  
  # AOP
  pod 'Aspects', '~> 1.4.1'
  
  #文本适配
  pod 'YYText', '~> 1.0.7'
  
  pod 'MBProgressHUD', '~> 1.1.0'
  
  
  # 播放器
  pod 'ZFPlayer', '~> 3.2.6'
  pod 'ZFPlayer/ControlView', '~> 3.2.6'
  pod 'ZFPlayer/AVPlayer', '~> 3.2.6'
  
  # 极光
  pod 'JPush'

end
